Added kick command
NoelWriter/CSMW-Discord pull request #21
Opened 2020-09-14 18:33 UTC by nathanaelbaaij

2020-09-14 18:37 UTC, PHillemans commented on src/commands/utilities/kick.js
> +                    } catch {
```javascript
catch (e) {
    message.reply("I do not have permissions to kick " + member);
    console.log(e);
}

2020-09-15 16:52 UTC, NoelWriter requested changes

2020-09-15 16:52 UTC, NoelWriter commented on src/commands/utilities/kick.js
> +                        message.reply("I do not have permissions to kick " + member);
Voeg nog even >>> voor elke tekst svp. Dan ziet het er beter uit in discord. e.x 
`message.reply(">>> I do not have permissions to kick " + member);`

2020-09-15 16:52 UTC, NoelWriter commented on src/commands/utilities/kick.js
> +                message.reply("You do not have permissions to kick " + member);
Ook bij deze

2020-09-16 08:29 UTC, nathanaelbaaij commented
@NoelWriter >>> bij deze toegevoegd

2020-09-16 09:31 UTC, NoelWriter approved these changes
Toppie!

2020-09-16 09:31 UTC, merged